name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Change to master if applicable

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Adjust as needed
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build the site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Upload build output
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
